timezone: Europe/Rome
baseurl: /log
permalink: pretty
repository: trasparente/log

# DEFAULTS
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: posts
    values:
      metadata: true
      pagination: true

# COLLECTIONS
collections:
  docs:
    title: Docs
    output: true
  posts:
    title: Posts